---
  - name: My Fact Finder
    gather_facts: no
    hosts: csr
    tasks:
      - name: Register ansible facts
        setup:
        register: ansible_facts
      - name: Print Ansible facts
        debug:
          msg: "{{ ansible_facts }}"
      - name: Gather IOS facts
        vars:
          credentials:
            host: "{{ ansible_host }}"
            username: "{{ username }}"
            password: "{{ password }}"
        ios_facts:
          provider: "{{ credentials }}"
        register: ios_facts_output
      - name: Print IOS facts
        debug:
          msg: "{{ ios_facts_output }}"
